version: '3.8'

services:

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: KotlinSpringSecurity
    ports:
      - 27017:27017

  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb

  
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      

  keycloak:
   image: 'bitnami/keycloak:latest'
   ports: 
     - 80:8080

   environment: 
     - KEYCLOAK_CREATE_ADMIN_USER=true
     - KEYCLOAK_DATABASE_NAME=keycloak
     - KEYCLOAK_DATABASE_USER=postgres
     - KEYCLOAK_DATABASE_PASSWORD=password123
     - KEYCLOAK_USER=admin
     - KEYCLOAK_PASSWORD=admin
   depends_on: 
     -   postgresql


volumes:
   postgresql_data:
    driver: local
